---
# tasks file for nginx
- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - nginx

- name: Copy virtualhost file
  copy: src=files/default
        dest=/etc/nginx/sites-available/default

  notify:
    - restart nginx
