---
- hosts: db-dns
  become: true

  roles:
      - server
      - mariadb
      - bind9

- hosts: web
  become: true

  handlers:
    - name: start nginx
      service: name=nginx state=started

  roles:
      - server
      - nginx
      - fpm
