---
# tasks file for bind9
- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - bind9

- name: Bind9 zones configuration
  copy:
    src=named.conf.local
    dest=/etc/bind/named.conf.local

- name: Bind9 example.com dns
  template:
    src=example.com.j2
    dest=/var/cache/bind/example.com

- name: Restart Bind9
  systemd:
    name=bind9
    state=restarted
