---
# tasks file for mariadb
- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv={{ wp_mysql_db }}.*:ALL
    host="%"
    state=present

#se elimina en lugar de colocar una direccion de escucha (por las ips dinamicas)
- name: Allow external connections
  sudo: yes
  lineinfile:
    dest=/etc/mysql/mariadb.conf.d/50-server.cnf
    regexp="^bind-address"
    line="#bind-addres="

# - name: Restart mariadb
#   systemd:
#     name=mariadb
#     state=restarted
