---
- name: apt update
  apt: update_cache=yes

- name: detect requirements.yml
  stat:
    path: "{{playbook_dir}}/roles/requirements.yml"
  register: doesRequirementsExist

- name: fetch galaxy roles from requirements.yml
  command: ansible-galaxy install -r requirements.yml -p {{playbook_dir}}/roles/ --force
  args:
    chdir: "{{playbook_dir}}/roles"
  when: doesRequirementsExist.stat.exists
